version: "3.7"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /var/lib/postgresql/data
# networks:
#   default:
#     external: true
#     name: caddy
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8989:8080"
